// Code generated by MockGen. DO NOT EDIT.
// Source: rate_handler.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRateProviderService is a mock of IRateProviderService interface.
type MockIRateProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockIRateProviderServiceMockRecorder
}

// MockIRateProviderServiceMockRecorder is the mock recorder for MockIRateProviderService.
type MockIRateProviderServiceMockRecorder struct {
	mock *MockIRateProviderService
}

// NewMockIRateProviderService creates a new mock instance.
func NewMockIRateProviderService(ctrl *gomock.Controller) *MockIRateProviderService {
	mock := &MockIRateProviderService{ctrl: ctrl}
	mock.recorder = &MockIRateProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRateProviderService) EXPECT() *MockIRateProviderServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIRateProviderService) Get() (*float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIRateProviderServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIRateProviderService)(nil).Get))
}
