name: tests
on: [push, pull_request]

jobs:
    test:
        name: "Test execution"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with: 
                go-version: stable




